repos:
  - repo: local
    hooks:
      - id: format-backend
        name: Format Backend
        entry: make format_backend
        language: system
        pass_filenames: false

      - id: lint-backend
        name: Lint Backend
        entry: make lint_backend
        language: system
        pass_filenames: false

      - id: test-backend
        name: Test Backend
        entry: make test_backend
        language: system
        pass_filenames: false
