services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:443"
    volumes:
      - ./backend/src:/app/src
    environment:
      - ENV=development
      - LOGGER_CONFIG_PATH=config/logger.ini
    command:
      - poetry
      - run
      - uvicorn
      - mr_lim_card_game.main:app
      - --host
      - 0.0.0.0
      - --port
      - "443"
      - --ssl-certfile
      - src/certs/cert.pem
      - --ssl-keyfile
      - src/certs/key.pem
      - --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
