services:
  mr_lim_card_game:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    command: poetry run uvicorn mr_lim_card_game.main:app --host 0.0.0.0 --port 8000
